#!/bin/bash
ls -l
Total 8
drwxr-xr-x 5 root root 136 Oct 13 10:47 .
drwxr-xr-x 1 root root 163 Oct 11 09:13 ..
-rw-r--r-- 1 root root  13 Oct 12 12:58 0-hello_world
-rw-r--r-- 1 root root   0 Oct 13 10:47 3-listfiles
drwxr-xr-x 2 root root   6 Oct 11 13:08 bash
drwxr-xr-x 2 root root 116 Oct 13 06:56 basics
drwxr-xr-x 8 root root 166 Oct 13 07:00 .git
-rw-r--r-- 1 root root   0 Oct 12 12:54 io_redirections_and_filters
-rw-r--r-- 1 root root  21 Oct 11 13:28 README.md
